# Generated by Django 6.0.3 on 2026-04-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='passkey',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
